[package]
name = "ore-cli"
version = "0.4.9"
description = "A command line interface for the Ore program."
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "ore"
path = "src/main.rs"

[features]
default = []
admin = []

[dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
cached = "0.49.3"
chrono = "0.4.34"
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
log = "0.4"
ore = { version = "1.2.0", package = "ore-program" }
rand = "0.8.4"
solana-cli-config = "1.17.20"
solana-client = "^1.17.20"
solana-program = "^1.17.20"
solana-sdk = "^1.17.20"
solana-account-decoder = "^1.17.20"
solana-transaction-status = "^1.17.20"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] }
tokio = "1"
jito-searcher-client = { path = "../searcher_client" }
jito-protos = { path = "../jito_protos" }
tonic = "0.10"
